name: 'pipeline notifier slack'
description: 'notifies slack of pipeline status'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
    value: ${{ steps.timestamp.outputs.time }}
runs:
  using: 'composite'
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}
      shell: bash
    - id: time-stamp
      run: echo "time='this time is'" >> $GITHUB_OUTPUT
      shell: bash
    - run: ls -a
      shell: bash
